<datalist id="suggestedBank">
	<option value="Aareal Bank AG">
	<option value="Abc International Bank Plc">
	<option value="Aletti &amp; C. Banca di Investimento Mobiliare">
	<option value="Allfunds Bank S.A.">
	<option value="Allianz Bank Financial Advisors">
	<option value="Alpenbank A.G.">
	<option value="Artigiancassa">
	<option value="Attijariwafa Bank Europe Sede Secondaria Italiana">
	<option value="Banca 5">
	<option value="Banca Adria - Credito Cooperativo del Delta">
	<option value="Banca Agricola Popolare di Ragusa">
	<option value="Banca Akros">
	<option value="Banca Albertini Syz">
	<option value="Banca Alpi Marittime Credito Cooperativo Carru'">
	<option
		value="Banca Alto Vicentino - Credito Cooperativo di Schio, Pedemonte e Roana">
	<option value="Banca Apulia">
	<option value="Banca Cambiano 1884">
	<option value="Banca Capasso Antonio">
	<option value="Banca Carige - Cassa di Risparmio di Genova e Imperia">
	<option value="Banca Carim - Cassa di Risparmio di Rimini">
	<option value="Banca Cassa di Risparmio di Savigliano">
	<option value="Banca Centro Emilia - Credito Cooperativo">
	<option value="Banca Centro Lazio Credito Cooperativo">
	<option value="Banca Centropadana Credito Cooperativo">
	<option value="Banca Cesare Ponti">
	<option value="Banca Consulia">
	<option value="Banca Cras Credito Cooperativo Toscano - Siena">
	<option value="Banca Cremasca - Credito Cooperativo">
	<option
		value="Banca dei Colli Euganei - Credito Cooperativo - Lozzo Atestino">
	<option value="Banca dei Sibillini-Credito Cooperativo di Casavecchia">
	<option value="Banca del Catanzarese - Credito Cooperativo">
	<option value="Banca del Centroveneto - Credito Cooperativo - Longare">
	<option
		value="Banca del Cilento di Sassano e Vallo di Diano e della Lucania - Credito Cooperativo">
	<option value="Banca del Fermano - Credito Cooperativo">
	<option value="Banca del Fucino">
	<option value="Banca del Mezzogiorno - Mediocredito Centrale">
	<option value="Banca del Monte di Lucca">
	<option
		value="Banca del Nisseno Credito Cooperativo di Sommatino e Serradifalco">
	<option value="Banca del Piemonte">
	<option value="Banca del Sud">
	<option value="Banca del Territorio Lombardo Credito Cooperativo">
	<option value="Banca del Valdarno - Credito Cooperativo">
	<option value="Banca del Vomano - BCC Società Cooperativa per Azioni">
	<option value="Banca dell'Alta Murgia Credito Cooperativo">
	<option value="Banca dell'Elba Credito Cooperativo">
	<option value="Banca della Marca Credito Cooperativo">
	<option value="Banca della Nuova Terra">
	<option value="Banca della Provincia di Macerata">
	<option value="Banca della Valsassina Credito Cooperativo">
	<option value="Banca di Ancona, Credito Cooperativo">
	<option value="Banca di Andria di Credito Cooperativo">
	<option value="Banca di Anghiari e Stia - Credito Cooperativo">
	<option value="Banca di Bologna Credito Cooperativo">
	<option
		value="Banca di Caraglio, del Cuneese e della Riviera dei Fiori - Credito Cooperativo">
	<option value="Banca di Carnia e Gemonese - Credito Cooperativo">
	<option value="Banca di Credito Peloritano">
	<option value="Banca di Credito Popolare">
	<option
		value="Banca di Filottrano - Credito Cooperativo di Filottrano e Camerano">
	<option value="Banca di Forli' - Credito Cooperativo">
	<option
		value="Banca di Formello e Trevignano Romano di Credito Cooperativo">
	<option value="Banca di Imola">
	<option value="Banca di Monastier e del Sile - Credito Cooperativo">
	<option value="Banca di Parma - Credito Cooperativo">
	<option value="Banca di Pesaro Credito Cooperativo">
	<option value="Banca di Pescia e Cascina - Credito Cooperativo">
	<option value="Banca di Piacenza">
	<option value="Banca di Pisa e Fornacette Credito Cooperativo">
	<option value="Banca di Ripatransone - Credito Cooperativo">
	<option value="Banca di Salerno Credito Cooperativo">
	<option
		value="Banca di Sconto e Conti Correnti di Santa Maria Capua Vetere">
	<option value="Banca di Taranto - BCC">
	<option value="Banca di Udine Credito Cooperativo">
	<option value="Banca di Verona Credito Cooperativo Cadidavid">
	<option value="Banca di Viterbo Credito Cooperativo -SCPA">
	<option
		value="Banca Don Rizzo - Credito Cooperativo della Sicilia Occidentale">
	<option value="Banca Emilveneta">
	<option value="Banca Esperia">
	<option value="Banca Euromobiliare">
	<option value="Banca Federico del Vecchio">
	<option value="Banca Finanziaria Internazionale">
	<option value="Banca Finnat Euramerica">
	<option value="Banca Galileo">
	<option value="Banca Generali">
	<option value="Banca Ifigest">
	<option value="Banca Ifis">
	<option value="Banca Imi">
	<option value="Banca Intermobiliare di Investimenti e Gestioni">
	<option value="Banca Interprovinciale">
	<option value="Banca Leonardo">
	<option value="Banca Malatestiana - Credito Cooperativo">
	<option value="Banca Mediocredito del Friuli Venezia Giulia">
	<option value="Banca Mediolanum">
	<option value="Banca Monte dei Paschi di Siena">
	<option
		value="Banca Monte Pruno - Credito Cooperativo di Fisciano, Roscigno e Laurino">
	<option value="Banca Nazionale del Lavoro">
	<option value="Banca Nuova">
	<option value="Banca Passadore &amp; C.">
	<option
		value="Banca Patavina Credito Cooperatvo di Sant'Elena e Piove di Sacco">
	<option value="Banca Patrimoni Sella &amp; C.">
	<option value="Banca per lo Sviluppo della Cooperazione di Credito">
	<option value="Banca Piccolo Credito Valtellinese">
	<option value="Banca Picena Truentina Credito Cooperativo">
	<option value="Banca Popolare del Cassinate">
	<option value="Banca Popolare del Frusinate">
	<option value="Banca Popolare del Lazio">
	<option value="Banca Popolare dell'Alto Adige">
	<option value="Banca Popolare delle Province Molisane">
	<option value="Banca Popolare di Bari">
	<option value="Banca Popolare di Cividale">
	<option value="Banca Popolare di Cortona">
	<option value="Banca Popolare di Fondi">
	<option value="Banca Popolare di Lajatico">
	<option value="Banca Popolare di Milano">
	<option value="Banca Popolare di Puglia e Basilicata">
	<option value="Banca Popolare di Sondrio">
	<option value="Banca Popolare di Spoleto">
	<option value="Banca Popolare di Vicenza">
	<option value="Banca Popolare Etica">
	<option value="Banca Popolare Pugliese">
	<option value="Banca Popolare Sant'Angelo">
	<option value="Banca Popolare Valconca">
	<option value="Banca Popolare Vesuviana">
	<option value="Banca Privata Leasing">
	<option value="Banca Profilo">
	<option value="Banca Progetto">
	<option value="Banca Promos">
	<option value="Banca Prossima">
	<option value="Banca Reale">
	<option value="Banca Regionale di Sviluppo">
	<option
		value="Banca S. Biagio del Veneto Orientale di Cesarolo, Fossalta di Portogruaro e Pertegada - BCC">
	<option value="Banca San Francesco Credito Cooperativo">
	<option
		value="Banca San Giorgio Quinto Valle Agno - Credito Cooperativo">
	<option value="Banca Santa Giulia">
	<option
		value="Banca Santo Stefano - Credito Cooperativo - Martellago-Venezia">
	<option value="Banca Sella">
	<option value="Banca Sella Holding">
	<option value="Banca Simetica">
	<option value="Banca Sistema">
	<option value="Banca Stabiese">
	<option value="Banca Suasa - Credito Cooperativo">
	<option value="Banca Sviluppo Economico">
	<option value="Banca Sviluppo Tuscia">
	<option value="Banca Transilvania S.A.">
	<option value="Banca Ubae">
	<option
		value="Banca Valdichiana - Credito Cooperativo di Chiusi e Montepulciano">
	<option value="Banca Valsabbina">
	<option value="Banca Veronese Credito Cooperativo di Concamarise">
	<option
		value="Banca Versilia Lunigiana e Garfagnana - Credito Cooperativo">
	<option value="Banco Bilbao Vizcaya Argentaria S.A.">
	<option value="Banco Bpm">
	<option value="Banco delle Tre Venezie">
	<option value="Banco di Credito P.Azzoaglio">
	<option value="Banco di Desio e della Brianza">
	<option value="Banco di Lucca e del Tirreno">
	<option value="Banco di Napoli">
	<option value="Banco di Sardegna">
	<option value="Banco Do Brasil AG">
	<option
		value="Banco Fiorentino - Mugello Impruneta Signa - Credito Cooperativo">
	<option value="Banco Santander S.A.">
	<option value="Bank Of China Limited - Filiale di Milano o">
	<option value="Bank Of Scotland Plc">
	<option value="Bank Sepah">
	<option value="Banque Chaabi du Maroc - in ovvero, B.C.D.M.">
	<option value="Barclays Bank Plc">
	<option
		value="Bassano Banca Credito Cooperativo di Romano e Santa Caterina">
	<option value="Bayerische Landesbank">
	<option value="BCC 'G. Toniolo' di San Cataldo">
	<option value="BCC 'Giuseppe Toniolo' di Genzano">
	<option value="BCC 'S. Barnaba' di Marino">
	<option value="BCC 'S. Giuseppe' di Petralia Sottana">
	<option value="BCC 'Sen. Pietro Grammatico' di Paceco">
	<option value="BCC Abruzzese - Cappelle sul Tavo">
	<option value="BCC Agrigentino">
	<option value="BCC Agrobresciano">
	<option value="BCC Antonello da Messina">
	<option
		value="BCC Basilicata - Credito Cooperativo di Laurenzana e Comuni Lucani">
	<option value="BCC Bergamasca e Orobica">
	<option value="BCC Bergamo e Valli">
	<option value="BCC degli Ulivi - Terra di Bari">
	<option value="BCC dei Castelli e degli Iblei">
	<option value="BCC dei Castelli Romani e del Tuscolo">
	<option value="BCC dei Comuni Cilentani">
	<option value="BCC del Basso Sebino">
	<option value="BCC del Carso">
	<option value="BCC del Circeo">
	<option value="BCC del Friuli Centrale">
	<option value="BCC del Garda - BCC Colli Morenici del Garda">
	<option value="BCC del Metauro">
	<option value="BCC del Velino - Comune di Posta Provincia di Rieti">
	<option value="BCC dell'Adriatico Teramano">
	<option value="BCC dell'Alta Brianza - Alzate Brianza">
	<option value="BCC dell'Alto Reno">
	<option value="BCC dell'Alto Tirreno della Calabria Verbicaro">
	<option value="BCC dell'Oglio e del Serio">
	<option value="BCC della Bassa Friulana">
	<option value="BCC della Romagna Occidentale">
	<option value="BCC della Valle del Fitalia">
	<option value="BCC della Valle del Trigno">
	<option value="BCC delle Prealpi">
	<option value="BCC di Alba, Langhe, Roero e del Canavese">
	<option value="BCC di Alberobello e Sammichele di Bari">
	<option value="BCC di Altofonte e Caccamo">
	<option value="BCC di Anagni">
	<option value="BCC di Aquara">
	<option value="BCC di Arborea">
	<option value="BCC di Avetrana">
	<option value="BCC di Bari">
	<option value="BCC di Barlassina">
	<option value="BCC di Basciano">
	<option value="BCC di Basiliano">
	<option value="BCC di Bellegra">
	<option value="BCC di Borghetto Lodigiano">
	<option value="BCC di Brescia">
	<option value="BCC di Buccino">
	<option value="BCC di Buonabitacolo">
	<option value="BCC di Busto Garolfo e Buguggiate">
	<option value="BCC di Cagliari">
	<option value="BCC di Canosa - Loconia">
	<option value="BCC di Capaccio Paestum">
	<option value="BCC di Carate Brianza">
	<option value="BCC di Carugate e Inzago">
	<option value="BCC di Casalgrasso e Sant'Albano Stura">
	<option value="BCC di Cassano delle Murge e Tolve">
	<option value="BCC di Castagneto Carducci">
	<option value="BCC di Castiglione Messer Raimondo e Pianella">
	<option value="BCC di Cernusco sul Naviglio">
	<option value="BCC di Cherasco">
	<option value="BCC di Cittanova">
	<option value="BCC di Civitanova Marche e Montecosaro">
	<option value="BCC di Conversano">
	<option value="BCC di Corinaldo">
	<option value="BCC di Doberdo' e Savogna">
	<option value="BCC di Dovera e Postino">
	<option value="BCC di Falconara Marittina">
	<option value="BCC di Fano">
	<option value="BCC di Fiumicello ed Aiello del Friuli">
	<option value="BCC di Flumeri">
	<option value="BCC di Gambatesa">
	<option value="BCC di Gaudiano di Lavello">
	<option value="BCC di Gradara">
	<option value="BCC di Lesmo">
	<option value="BCC di Leverano">
	<option value="BCC di Lezzeno">
	<option value="BCC di Locorotondo Cassa Rurale e Artigiana">
	<option value="BCC di Manzano">
	<option value="BCC di Marina di Ginosa">
	<option value="BCC di Masiano">
	<option value="BCC di Massafra">
	<option value="BCC di Monopoli">
	<option value="BCC di Montepaone">
	<option value="BCC di Mozzanica">
	<option value="BCC di Napoli">
	<option value="BCC di Nettuno">
	<option value="BCC di Oppido Lucano e Ripacandida">
	<option value="BCC di Ostra e Morro d'Alba">
	<option value="BCC di Ostra Vetere">
	<option value="BCC di Ostuni">
	<option value="BCC di Pachino">
	<option value="BCC di Pergola">
	<option value="BCC di Pianfei e Rocca de' Baldi">
	<option value="BCC di Pontassieve">
	<option value="BCC di Pratola Peligna">
	<option value="BCC di Putignano">
	<option value="BCC di Recanati e Colmurano">
	<option value="BCC di Riano">
	<option
		value="BCC di Rivarolo Canavese, Rivara ed Enti Territoriali Locali - Riva Banca">
	<option value="BCC di Roma">
	<option value="BCC di Ronciglione e Barbarano Romano">
	<option value="BCC di Sambuca di Sicilia">
	<option value="BCC di San Biagio Platani">
	<option value="BCC di San Giovanni Rotondo">
	<option value="BCC di San Marco dei Cavoti e del Sannio-Calvi">
	<option value="BCC di San Marzano di San Giuseppe - Taranto">
	<option value="BCC di Santeramo in Colle">
	<option value="BCC di Sarsina">
	<option value="BCC di Scafati e Cetara">
	<option value="BCC di Serino">
	<option value="BCC di Sesto San Giovanni">
	<option value="BCC di Spello e Bettona">
	<option value="BCC di Spinazzola">
	<option value="BCC di Staranzano e Villesse">
	<option value="BCC di Terra d'Otranto">
	<option value="BCC di Triuggio e della Valle del Lambro">
	<option value="BCC di Turriaco">
	<option value="BCC di Valledolmo">
	<option value="BCC di Venezia, Padova e Rovigo - Banca Annia">
	<option value="BCC di Vergato">
	<option value="BCC di Vignole e della Montagna Pistoiese">
	<option value="BCC Don Stella di Resuttano">
	<option value="BCC Felsinea - BCC Dal1902">
	<option value="BCC la Riscossa di Regalbuto">
	<option value="BCC Laudense - Lodi">
	<option value="BCC Mutuo Soccorso di Gangi">
	<option value="BCC Picena">
	<option value="BCC Pordenonese">
	<option value="BCC Privernate">
	<option value="BCC San Giuseppe di Mussomeli">
	<option value="BCC San Michele di Caltanissetta e Pietraperzia">
	<option value="BCC Sangro Teatina di Atessa">
	<option value="BCC Terra di Lavoro - S. Vincenzo de' Paoli">
	<option value="BCC Umbria Credito Cooperativo">
	<option value="BCC Valdostana - Cooperative De Credit Valdotaine">
	<option value="BCC Valle del Torto">
	<option value="BCC Vicentino - Pojana Maggiore">
	<option value="Bene Banca Credito Cooperativo di Bene Vagienna">
	<option value="Bhw Bausparkasse AG">
	<option value="Binckbank NV">
	<option value="Bmw Bank GmbH">
	<option value="Bnp Paribas">
	<option value="Bnp Paribas Lease Group">
	<option value="Bnp Paribas Securities Services">
	<option value="BPER Banca">
	<option value="Bsi Europe S.A.">
	<option value="Ca Indosuez Wealth">
	<option value="Caceis Bank">
	<option value="Carilo - Cassa di Risparmio di Loreto">
	<option value="Carrefour Banque">
	<option value="Cassa Centrale Banca - Credito Cooperativo del Nord Est">
	<option
		value="Cassa Centrale Raiffeisen dell'Alto Adige - Raiffeisen-Landesbank Suedtirol A.G.">
	<option value="Cassa dei Risparmi di Forli' e della Romagna">
	<option value="Cassa di Risparmio del Friuli Venezia Giulia">
	<option value="Cassa di Risparmio del Veneto">
	<option value="Cassa di Risparmio di Asti">
	<option value="Cassa di Risparmio di Biella e Vercelli - Biverbanca">
	<option value="Cassa di Risparmio di Bolzano - Sudtiroler Sparkasse AG">
	<option value="Cassa di Risparmio di Bra">
	<option value="Cassa di Risparmio di Cento">
	<option value="Cassa di Risparmio di Cesena">
	<option value="Cassa di Risparmio di Fermo">
	<option value="Cassa di Risparmio di Firenze">
	<option value="Cassa di Risparmio di Fossano">
	<option value="Cassa di Risparmio di Orvieto">
	<option value="Cassa di Risparmio di Pistoia e della Lucchesia">
	<option value="Cassa di Risparmio di Ravenna">
	<option value="Cassa di Risparmio di Saluzzo">
	<option value="Cassa di Risparmio di San Miniato">
	<option value="Cassa di Risparmio di Volterra">
	<option value="Cassa di Risparmio in Bologna">
	<option
		value="Cassa di Sovvenzioni e Risparmio Fra il Personale della Banca d'Italia">
	<option value="Cassa Lombarda">
	<option value="Cassa Padana BCC">
	<option value="Cassa Raiffeisen Alta Pusteria">
	<option value="Cassa Raiffeisen Alta Venosta">
	<option value="Cassa Raiffeisen Bassa Atesina">
	<option value="Cassa Raiffeisen Bassa Vall'Isarco">
	<option value="Cassa Raiffeisen Campo di Trens">
	<option
		value="Cassa Raiffeisen Castelrotto - Ortisei - Raiffeisenkasse Kastelruth - St. Ulrich Genossenschaft">
	<option value="Cassa Raiffeisen della Val Passiria">
	<option value="Cassa Raiffeisen della Valle Isarco">
	<option value="Cassa Raiffeisen di Brunico">
	<option value="Cassa Raiffeisen di Ciardes">
	<option value="Cassa Raiffeisen di Dobbiaco">
	<option value="Cassa Raiffeisen di Funes">
	<option value="Cassa Raiffeisen di Lagundo">
	<option value="Cassa Raiffeisen di Lasa">
	<option value="Cassa Raiffeisen di Marlengo">
	<option value="Cassa Raiffeisen di Monguelfo-Casies-Tesido">
	<option value="Cassa Raiffeisen di Naturno">
	<option value="Cassa Raiffeisen di Nova Ponente-Aldino">
	<option value="Cassa Raiffeisen di Parcines">
	<option value="Cassa Raiffeisen di San Martino in Passiria">
	<option value="Cassa Raiffeisen di Scena">
	<option value="Cassa Raiffeisen di Senales">
	<option value="Cassa Raiffeisen di Tesimo">
	<option value="Cassa Raiffeisen di Vandoies">
	<option value="Cassa Raiffeisen di Villabassa">
	<option value="Cassa Raiffeisen Etschtal">
	<option value="Cassa Raiffeisen Laces">
	<option value="Cassa Raiffeisen Lana">
	<option value="Cassa Raiffeisen Merano">
	<option value="Cassa Raiffeisen Oltradige">
	<option value="Cassa Raiffeisen Prato-Tubre">
	<option value="Cassa Raiffeisen Schlern - Rosengarten">
	<option value="Cassa Raiffeisen Silandro">
	<option value="Cassa Raiffeisen Tirolo">
	<option value="Cassa Raiffeisen Tures-Aurina">
	<option value="Cassa Raiffeisen Ultimo - S. Pancrazio - Lauregno">
	<option value="Cassa Raiffeisen Val Badia - Genossenschaft">
	<option value="Cassa Raiffeisen Val Gardena">
	<option value="Cassa Raiffeisen Val Sarentino">
	<option value="Cassa Raiffeisen Wipptal">
	<option value="Cassa Rurale - BCC di Treviglio">
	<option value="Cassa Rurale Adamello - Brenta BCC">
	<option
		value="Cassa Rurale Alta Vallagarina di Besenello, Calliano, Nomi, Volano - BCC">
	<option value="Cassa Rurale Alta Valsugana - BCC">
	<option value="Cassa Rurale Alto Garda - BCC">
	<option value="Cassa Rurale Bassa Anaunia - BCC">
	<option value="Cassa Rurale Bassa Vallagarina BCC">
	<option value="Cassa Rurale Centrofiemme - Cavalese - BCC">
	<option value="Cassa Rurale d'Anaunia - BCC Taio">
	<option value="Cassa Rurale degli Altipiani - BCC">
	<option value="Cassa Rurale di Bolzano">
	<option value="Cassa Rurale di Fiemme - BCC">
	<option value="Cassa Rurale di Giovo - BCC">
	<option value="Cassa Rurale di Isera - BCC">
	<option value="Cassa Rurale di Ledro - BCC">
	<option value="Cassa Rurale di Lizzana - BCC">
	<option value="Cassa Rurale di Mezzocorona - BCC">
	<option
		value="Cassa Rurale di Mezzolombardo e San Michele all'Adige - BCC">
	<option value="Cassa Rurale di Rovere' della Luna - BCC">
	<option value="Cassa Rurale di Rovereto - BCC">
	<option value="Cassa Rurale di Salorno">
	<option value="Cassa Rurale di Saone - BCC">
	<option value="Cassa Rurale di Tassullo e Nanno - BCC">
	<option value="Cassa Rurale di Trento - BCC">
	<option value="Cassa Rurale di Tuenno - Val di non - BCC">
	<option
		value="Cassa Rurale Don Lorenzo Guetti di Quadra - Fiave' - Lomaso - BCC">
	<option
		value="Cassa Rurale e Artigiana di Brendola Credito Cooperativo">
	<option
		value="Cassa Rurale ed Artigiana - BCC di Battipaglia e Montecorvino Rovella">
	<option value="Cassa Rurale ed Artigiana dell'Agro Pontino - BCC">
	<option
		value="Cassa Rurale ed Artigiana di Binasco - Credito Cooperativo">
	<option
		value="Cassa Rurale ed Artigiana di Borgo San Giacomo - Credito Cooperativo">
	<option value="Cassa Rurale ed Artigiana di Boves - BCC">
	<option value="Cassa Rurale ed Artigiana di Cantu' BCC">
	<option
		value="Cassa Rurale ed Artigiana di Castellana Grotte Credito Cooperativo">
	<option
		value="Cassa Rurale ed Artigiana di Cortina d'Ampezzo e delle Dolomiti - Credito Cooperativo">
	<option
		value="Cassa Rurale ed Artigiana di Rivarolo Mantovano Credito Cooperativo">
	<option
		value="Cassa Rurale ed Artigiana di Vestenanova - Credito Cooperativo">
	<option value="Cassa Rurale Giudicarie Valsabbia Paganella - BCC">
	<option value="Cassa Rurale Lavis - Valle di Cembra - BCC">
	<option value="Cassa Rurale Novella e Alta Anaunia - BCC">
	<option value="Cassa Rurale Pinzolo - BCC">
	<option value="Cassa Rurale Renon">
	<option value="Cassa Rurale Val di Fassa e Agordino - BCC">
	<option value="Cassa Rurale Val di Sole - BCC">
	<option value="Cassa Rurale Val Rendena - BCC">
	<option value="Cassa Rurale Valli di Primiero e Vanoi - BCC">
	<option value="Cassa Rurale Valsugana e Tesino - BCC">
	<option value="Centromarca Banca - Credito Cooperativo di Treviso">
	<option value="Cereabanca 1897 Credito Cooperativo">
	<option value="Chebanca!">
	<option value="Chiantibanca - Credito Cooperativo">
	<option value="Citibank N.A.">
	<option value="Claas Financial Services">
	<option value="Cnh Industrial Capital Europe">
	<option value="Cnh Industrial Financial Services S.A.">
	<option value="Commerzbank AG">
	<option value="Compass Banca">
	<option value="Cooperatieve Rabobank U.A.">
	<option value="Credit Agricole Carispezia">
	<option value="Credit Agricole Corporate &amp; Investment Bank">
	<option value="Credit Agricole Friuladria">
	<option value="Credit Suisse">
	<option value="Credit Suisse AG">
	<option
		value="Credito Cooperativo - Cassa Rurale ed Artigiana di Lucinico, Farra e Capriva">
	<option value="Credito Cooperativo Cassa Rurale ed Artigiana di Erchie">
	<option
		value="Credito Cooperativo Cassa Rurale ed Artigiana di Paliano">
	<option value="Credito Cooperativo Centro Calabria">
	<option
		value="Credito Cooperativo di Caravaggio Adda e Cremasco - Cassa Rurale">
	<option
		value="Credito Cooperativo di San Calogero e Maierato - BCC del Vibonese">
	<option value="Credito Cooperativo Friuli">
	<option value="Credito Cooperativo Mediocrati">
	<option value="Credito Cooperativo Ravennate ed Imolese">
	<option value="Credito Cooperativo Reggiano">
	<option value="Credito Cooperativo Romagnolo - BCC di Cesena e Gatteo">
	<option value="Credito Cooperativo Valdarno Fiorentino Banca di Cascia">
	<option value="Credito di Romagna">
	<option value="Credito Emiliano">
	<option value="Credito Etneo - BCC">
	<option value="Credito Fondiario">
	<option value="Credito Lombardo Veneto">
	<option value="Credito Padano BCC">
	<option value="Credito Siciliano">
	<option value="Credito Trevigiano - BCC">
	<option
		value="Credito Valdinievole BCC di Montecatini Terme e Bientina">
	<option value="Crédit Agricole Cariparma">
	<option value="De Lage Landen International B.V.">
	<option value="Deutsche Bank">
	<option value="Deutsche Bank AG">
	<option value="Deutsche Bank Mutui">
	<option value="Dobank">
	<option value="Edmond De Rothschild">
	<option value="Emil Banca - Credito Cooperativo">
	<option value="Europe Arab Bank Plc - Milan Branch">
	<option value="Extrabanca">
	<option value="Farbanca">
	<option value="Fce Bank Plc">
	<option value="Fideuram - Intesa Sanpaolo Private Banking">
	<option value="Finanza e Futuro Banca">
	<option value="Findomestic Banca">
	<option value="Finecobank Banca Fineco">
	<option value="Friulovest Banca - Credito Cooperativo">
	<option value="Gbm Banca">
	<option value="Hsbc Bank Plc">
	<option value="Hypo Alpe-Adria-Bank">
	<option value="Hypo Tirol Bank AG">
	<option value="IBL Istituto Bancario del Lavoro">
	<option
		value="ICCREA Banca - Istituto Centrale del Credito Cooperativo">
	<option value="ICCREA Bancaimpresa">
	<option value="Igea Banca">
	<option value="Ikb Deutsche Industriebank Aktiengesellschaft">
	<option value="Imprebanca">
	<option value="Industrial And Commercial Bank Of China S.A.">
	<option value="Ing Bank NV">
	<option value="Interbanca">
	<option value="Intesa Sanpaolo">
	<option value="Intesa Sanpaolo Private Banking">
	<option value="Invest Banca">
	<option value="Istituto Centrale delle Banche Popolari Italiane">
	<option
		value="Istituto per il Credito Sportivo - Ente di Diritto Pubblico">
	<option value="IW Bank">
	<option value="J.P. Morgan International Bank Limited">
	<option value="J.P. Morgan Securities Plc">
	<option value="Jcb Finance">
	<option value="Jpmorgan Chase Bank, National Association">
	<option value="La BCC del Crotonese - Credito Cooperativo">
	<option value="Mainfirst Bank Aktiengesellschaft">
	<option value="Mantovabanca 1896 Credito Cooperativo">
	<option value="Mediobanca - Banca di Credito Finanziario">
	<option value="Mediocredito Italiano">
	<option value="Mediocredito Trentino-Alto Adige">
	<option value="Mizuho Bank Limited">
	<option
		value="Monte dei Paschi di Siena Leasing &amp; Factoring, Banca per i Servizi Finanziari alle Imprese">
	<option
		value="Morgan Stanley Bank International Limited - Milan Branch">
	<option value="MPS Capital Services Banca per le Imprese">
	<option value="Natixis Lease S.A. - Succursale Italia">
	<option value="Natixis S.A.">
	<option value="Nomura Bank International Plc Italian Branch">
	<option value="Nova Ljubljanska Banka D.D., Ljubljana">
	<option value="Nuova Banca dell'Etruria e del Lazio">
	<option value="Nuova Banca delle Marche">
	<option value="Nuova Cassa di Risparmio di Chieti">
	<option value="Nuova Cassa di Risparmio di Ferrara">
	<option value="Pictet &amp; Cie S.A.">
	<option value="Prader Bank">
	<option value="Rbc Investor Services Bank S.A.">
	<option value="Rci Banque S.A.">
	<option
		value="Riminibanca - Credito Cooperativo di Rimini e Valmarecchia">
	<option
		value="Romagnabanca Credito Cooperativo Romagna Est e Sala di Cesenatico">
	<option value="Rovigobanca Credito Cooperativo - Soc. Coop">
	<option value="Sanfelice 1893 Banca Popolare">
	<option value="Santander Consumer Bank">
	<option value="Santander Private Banking <i>in liquidazione</i>">
	<option value="Saxo Bank A/S">
	<option value="Societe Generale Mutui Italia">
	<option value="Societe' Generale">
	<option value="Societe' Generale Securities Services">
	<option value="Standard Chartered Bank">
	<option value="State Street Bank International GmbH Succursale Italia">
	<option value="Sumitomo Mitsui Banking Corporation Europe Limited">
	<option value="Terre Etrusche e di Maremma C.C.">
	<option value="The Bank Of Tokyo - Mitsubishi Ufj, Ltd.">
	<option value="The Royal Bank Of Scotland Plc">
	<option value="Toyota Kreditbank GmbH">
	<option value="Ubi Banca">
	<option value="Ubs Europe Se">
	<option value="Unicredit">
	<option value="Unicredit Bank AG">
	<option value="Union Bancaire Privee S.A.">
	<option value="Unione di Banche Italiane">
	<option value="Unipol Banca">
	<option value="Valpolicella Benaco Banca Credito Cooperativo">
	<option value="Veneto Banca">
	<option value="Vibanca - BCC di San Pietro in Vincio">
	<option value="Vivibanca">
	<option value="Volkswagen Bank GmbH.">
</datalist>